In [1]:
import numpy as np
import matplotlib.pyplot as plt 

In [9]:
X = np.array([2,4,6,8,10])
Y = np.array([3,6,9,12,15])
Z = np.array([9,7,5,3,1])

mat = np.vstack((X, Y, Z))
#work with the transpose since the column should represent the feature vectors 
m = np.mean(mat.T,axis=0)
mat.T, m

(array([[ 2,  3,  9],
        [ 4,  6,  7],
        [ 6,  9,  5],
        [ 8, 12,  3],
        [10, 15,  1]]),
 array([6., 9., 5.]))

In [10]:
k = mat.T - m
covar_matrix = k.T.dot(k) / k.shape[0]

In [11]:
covar_matrix

array([[  8.,  12.,  -8.],
       [ 12.,  18., -12.],
       [ -8., -12.,   8.]])